DROP DATABASE IF EXISTS annuaire_cubes;
CREATE DATABASE IF NOT EXISTS annuaire_cubes;

CREATE TABLE IF NOT EXISTS Service(
	id_service INT NOT NULL AUTO_INCREMENT,
	nom_service VARCHAR(50) NOT NULL,
	date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_modification DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT id_service_pk PRIMARY KEY (id_service)
);

CREATE TABLE IF NOT EXISTS Site(
	id_site INT NOT NULL AUTO_INCREMENT,
	nom_site VARCHAR(50) NOT NULL,
	ville VARCHAR(100) NOT NULL,
	date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_modification DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT id_site_pk PRIMARY KEY (id_site)
);

CREATE TABLE IF NOT EXISTS Salarie(
	id_salarie INT NOT NULL AUTO_INCREMENT,
	nom VARCHAR(100) NOT NULL,
	prenom VARCHAR(100) NOT NULL,
	tel_fixe INT DEFAULT NULL,
	tel_portable INT NOT NULL,
	email VARCHAR(150) NOT NULL,
	service INT NOT NULL,
	site INT NOT NULL,
	date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_modification DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT id_salarie_pk PRIMARY KEY (id_salarie),
	CONSTRAINT id_salarie_service_fk FOREIGN KEY (service) REFERENCES Service(id_service),
	CONSTRAINT id_salarie_site_fk FOREIGN KEY (site) REFERENCES Site(id_site)
);

CREATE TABLE IF NOT EXISTS Admin(
	id_admin INT NOT NULL AUTO_INCREMENT,
	password_hasgh TEXT NOT NULL,
	date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_modification DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT id_admin_pk PRIMARY KEY (id_admin)
);